#!/usr/bin/env python3
"""
sync_console.py [file.html ...]

The console page now compiles Brainfuck itself, which means it carries a second
copy of the leaf blocks and scaffold cells. A second copy is a second thing that
can drift: when BLOCK_IN changed from 마/밯 to 무/붛, every alphabet index past
position 9 shifted and a page with the stale constant decoded good PNGs into
garbage. So neither copy is typed by hand -- both the ALPHABET constant and the
generated block region are written from bf_to_aheui.py's own values.

Run this after any change to bf_to_aheui.py. bf_to_png.py --sync calls it too.
"""
import re
import sys

import bf_to_aheui as C

BEGIN_MARK = '// >>> generated by sync_console.py from bf_to_aheui.py'
END_MARK = '// <<< end generated'

SCAFFOLD = ('DUP_SKIP2', 'NOOP_RIGHT', 'NOOP_LEFT', 'NOOP_DOWN',
            'NOOP_UP', 'CHECK_DOWN', 'CHECK_UP')
LEAVES = (('+', 'BLOCK_PLUS'), ('-', 'BLOCK_MINUS'), ('.', 'BLOCK_OUT'),
          (',', 'BLOCK_IN'), ('>', 'BLOCK_RIGHT'), ('<', 'BLOCK_LEFT'))


def js_str(s):
    """Escape to \\uXXXX so the file stays readable in any editor or encoding."""
    return '"%s"' % ''.join('\\n' if c == '\n' else c if c == ' ' else
                            '\\u%04X' % ord(c) for c in s)


def alphabet():
    syms = set()
    for _tok, name in LEAVES:
        for row in getattr(C, name):
            syms |= set(row)
    for name in ('BLOCK_HALT', 'BLOCK_BEGIN'):
        for row in getattr(C, name):
            syms |= set(row)
    for name in SCAFFOLD:
        syms.add(getattr(C, name))
    return ''.join(sorted(syms | {' ', '\n'}))


def block_js():
    out = [BEGIN_MARK]
    for name in SCAFFOLD:
        out.append('const %s = %s;' % (name, js_str(getattr(C, name))))
    out.append('const BLOCK_BEGIN = %s, BLOCK_HALT = %s;'
               % (js_str(C.BLOCK_BEGIN[0]), js_str(C.BLOCK_HALT[0])))
    out.append('const BLOCKS = {')
    for tok, name in LEAVES:
        rows = ', '.join(js_str(r) for r in getattr(C, name))
        out.append("  '%s': [%s]," % (tok, rows))
    out.append('};')
    out.append(END_MARK)
    return '\n'.join(out)


def sync(path):
    src = open(path, encoding='utf-8').read()
    done = []

    new, n = re.subn(r'const\s+ALPHABET\s*=\s*"[^"]*";',
                     lambda _m: 'const ALPHABET = %s;' % js_str(alphabet()),
                     src, count=1)
    if n:
        src = new
        done.append('ALPHABET')

    pat = re.compile(re.escape(BEGIN_MARK) + r'.*?' + re.escape(END_MARK), re.S)
    new, n = pat.subn(lambda _m: block_js(), src, count=1)
    if n:
        src = new
        done.append('blocks')

    if done:
        open(path, 'w', encoding='utf-8').write(src)
    return done


if __name__ == '__main__':
    args = sys.argv[1:]
    check = '--check' in args
    targets = [a for a in args if not a.startswith('-')] or ['aheui_console.html']
    stale = 0
    for t in targets:
        if check:
            src = open(t, encoding='utf-8').read()
            want_a = 'const ALPHABET = %s;' % js_str(alphabet())
            ok = want_a in src and block_js() in src
            print(f'{t}: {"up to date" if ok else "STALE -- run sync_console.py"}')
            stale += not ok
        else:
            d = sync(t)
            print(f'{t}: {"synced " + " + ".join(d) if d else "nothing to sync"}')
    sys.exit(1 if stale else 0)
